### PR TITLE
support redis auth, ttl sync, speed control

### PR DESCRIPTION
**Pull request by henter**
Fork Update

support redis auth
support ttl sync
sync speed control

Thanks.

### CODE REVIEW

**Comment by ajimix** [comment]
@nixtrace any chance of merging this?

**Comment by gingerlime** [comment]
Is the project dead? can't see much activity for a while now ...

**Comment by nixtrace** [comment]
Hi, thanks for the PR!

We will take a look soon.

**Comment by nixtrace** [comment]
Hi!

We just refactored and released Rump 1.0.0 with TTL sync, auth and many other features.
The codebase is very different than before, this PR can't be merged.

Thanks!

**Pull request closed without merging**
