### PR TITLE
tls: add option to connect to redis with enabled tls and auth token

### PR DESCRIPTION
**Pull request by lanycrost**
- [x] I have read the [contributing](docs/CONTRIBUTING.md) guide.
- [x] Issue: https://github.com/stickermule/rump/issues/41

### Implementation

- radix version is upgraded to `v3.7.1` and tested in real environment.
- added auth field to redis [Resource struct](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/config/config.go#L13-L17).
- added new function for retrieving [redis url and auth token](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/config/config.go#L38-L57) in connection string. [It's done for avoiding code duplication](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/config/config.go#L69-L70).
- added new test case for checking [how validation works with auth token](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/config/config_test.go#L51-L80).
- when connecting to redis with auth token we need to define callback to perform authentication and encryption [as described here](https://pkg.go.dev/github.com/mediocregopher/radix.v3#hdr-AUTH_and_other_settings_via_ConnFunc_and_ClientFunc). [Here is implementation](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/run/run.go#L27-L35)
- [Here I check](https://github.com/lanycrost/rump/blob/cc2bbe39d09adc57213aba948348c6d412af59d1/pkg/run/run.go#L53-L68) if auth is enabled we use ConnFunc described above, or your method without authentication (same for target).

Thanks!

### CODE REVIEW

**Comment by yuyuvn** [comment]
It's break auth without TLS support.

For TLS connection, redis url should use `rediss://` instead of `redis://`

**Comment by lanycrost** [comment]
@yuyuvn it's not braking, I have tested it in both ways, and yes you should use `rediss://` for TLS connections which is not available in current version of rump.

**Comment by yuyuvn** [comment]
@lanycrost
Did you test connect to redis server without TLS and have auth?
for example: `redis://user:password@127.0.0.1:6379` 
`strings.Contains(conn, authSeparator)` -> this condition will return true, so rump will connect via tls, which is not expected.

> and yes you should use rediss:// for TLS connections which is not available in current version of rump.
How about implement that in your pull-request?
Instead of check `@` to determine user want to use TLS or not, check if prefix is `rediss` or not should be better.

**Comment by lanycrost** [comment]
@yuyuvn sorry you are right, fixed.

**Pull request closed without merging**
